language: julia

os:
    - linux

julia:
    - 1.1
    - 1.2
    - nightly

addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python3 # python 3.5

matrix:
    allow_failures:
        - julia: nightly

fast_finish: true
notifications:
    email: false
    
script:
    - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test(coverage=true)'
   
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
